### ISSUE TITLE
Leak

### ISSUE THREAD

**Issue by obilodeau** [nsec/nsec-badge#1]
https://github.com/nsec/nsec-badge/blob/7a2f7601874b1e2cf20599a2e3ec0ffa3dc4f5e5/nrf52/led_code_storage.h#L45

:open_mouth:

**Comment by marc-etienne** [comment]
nsec18 is finished
<img width="492" alt="screen shot 2018-10-01 at 3 26 59 pm" src="https://user-images.githubusercontent.com/45015/46310853-8871fe00-c58e-11e8-8188-e66fbe0243bf.png">

**Comment by cashew22** [comment]
Hahahahaa
